const projectData = [
  { id: 'carnaval', title: 'Carnaval', category: 'Dashboard', summary: 'Painel para acompanhamento operacional dos atendimentos de saúde durante o carnaval.', image: 'imagens/dashboards-em-destaque/carnaval.svg', tags: ['Qlik Sense', 'Saúde', 'Monitoramento'] },
  { id: 'tuberculose', title: 'Tuberculose', category: 'Dashboard', summary: 'Acompanhamento epidemiológico e operacional para apoiar ações de busca ativa.', image: 'imagens/dashboards-em-destaque/tuberculose.svg', tags: ['Qlik Sense', 'Saúde Pública', 'Busca Ativa'] },
  { id: 'saude-coletiva', title: 'Saúde Coletiva', category: 'Dashboard', summary: 'Análise de tendências e indicadores epidemiológicos para a gestão de saúde pública.', image: 'imagens/dashboards-em-destaque/saude-coletiva.svg', tags: ['Python', 'Saúde Coletiva', 'Análise de Dados'] },
  { id: 'planejamento-recursos', title: 'Planejamento de Recursos para Veículos', category: 'Dashboard', summary: 'Visão de capacidade, alocação e demanda para planejamento de pessoas.', image: 'imagens/dashboards-em-destaque/planejamento-recursos.svg', tags: ['Power BI', 'DAX', 'Gestão de Pessoas'] },
  { id: 'pmo-dados', title: 'PMO da equipe de desenvolvimento de dados', category: 'Dashboard', summary: 'Acompanhamento estratégico de projetos, entregas e performance da equipe.', image: 'imagens/dashboards-em-destaque/pmo-dados.svg', tags: ['Tableau', 'PMO', 'Gestão'] },
  { id: 'obitos-predicao', title: 'Óbitos com Predição', category: 'Predição', summary: 'Pipeline analítico para antecipar tendências de óbitos e apoiar o planejamento em saúde.', image: 'imagens/predicoes-em-destaque/obitos-predicao.svg', tags: ['Alteryx', 'Predição', 'Saúde'] },
  { id: 'previsao-gasto-empresa', title: 'Previsão de Gasto da Empresa', category: 'Predição', summary: 'Modelo conceitual para estimar gastos futuros e apoiar o planejamento orçamentário.', image: 'imagens/predicoes-em-destaque/previsao-gasto-empresa.svg', tags: ['IA', 'Ciência de Dados', 'Financeiro'] },
  { id: 'previsao-valor-acao', title: 'Previsão de Valor de Ação', category: 'Predição', summary: 'Simulação de cenários para análise de comportamento e tendência de ativos.', image: 'imagens/predicoes-em-destaque/previsao-valor-acao.svg', tags: ['Modelagem', 'Mercado Financeiro', 'Previsão'] },
  { id: 'zapflow', title: 'Zapflow', category: 'Aplicativo', summary: 'Aplicativo para comunicação em escala pelo WhatsApp Web a partir de planilhas.', image: 'imagens/aplicativos-desenvolvidos/zapflow.svg', tags: ['Automação', 'WhatsApp Web', 'Excel'] },
  { id: 'horacerta', title: 'HoraCerta', category: 'Aplicativo', summary: 'Aplicativo para consulta, simulação e acompanhamento de banco de horas.', image: 'imagens/aplicativos-desenvolvidos/horacerta.svg', tags: ['Gestão', 'Banco de Horas', 'Produtividade'] },
  { id: 'flowproject', title: 'FlowProject', category: 'Aplicativo', summary: 'Aplicativo para gerenciar projetos de BI, análise, ciência de dados e programação, centralizando demandas, status e prioridades.', image: 'imagens/aplicativos-desenvolvidos/flowdesk.svg', tags: ['Power Apps', 'Projetos', 'Workflow'] },
  { id: 'governanca-acesso', title: 'Governança de Acesso com Power Platform', category: 'Automação', summary: 'Fluxo de gestão de acessos, perfis e aprovações integrado ao ecossistema Microsoft.', image: 'imagens/automacoes-desenvolvidas/governanca-acesso.svg', tags: ['Power Apps', 'Power Automate', 'Microsoft Lists'] },
  { id: 'preenchimento-formularios', title: 'Preenchimento de Formulários em Massa', category: 'Automação', summary: 'Fluxo para preencher e submeter formulários online a partir de dados estruturados.', image: 'imagens/automacoes-desenvolvidas/preenchimento-formularios.svg', tags: ['Automação', 'Planilha', 'Formulário Online'] },
  { id: 'disparo-email-massa', title: 'Disparo de E-mails em Massa', category: 'Automação', summary: 'Automação de comunicações recorrentes com personalização a partir de planilhas.', image: 'imagens/automacoes-desenvolvidas/disparo-email-massa.svg', tags: ['Comunicação', 'E-mail', 'Planilha'] }
];
